MedicalCenter/Controllers/LaboratoryPatientController.cs
using MedicalCenter.Areas.Administrator.Models;
using MedicalCenter.Core.Contracts;
using MedicalCenter.Core.Models.LaboratoryPatient;
using MedicalCenter.Extensions;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using static MedicalCenter.Infrastructure.Data.Global.DataConstants;

namespace MedicalCenter.Controllers
{
    public class LaboratoryPatientController : BaseController
    {
        private readonly ILaboratoryPatient laboratoryPatientService;

        public LaboratoryPatientController(ILaboratoryPatient _laboratoryPatientService)
        {
            laboratoryPatientService = _laboratoryPatientService;
        }

        [HttpGet]
        [AllowAnonymous]
        public IActionResult Login()
        {
            var loginModel = new LoginPatientViewModel();

            ViewData["Title"] = "Вход";

            return View(loginModel);
        }

        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> Login(LoginPatientViewModel loginModel)
        {
            if (!ModelState.IsValid)
            {
                ViewData["Title"] = "Вход";
                ModelState.AddModelError("", ModelErrorConstants.ViewModelError);
                return View(loginModel);
            }

            if (!await laboratoryPatientService.IsEgnExistAsync(loginModel.Egn) && !await laboratoryPatientService.IsUsernameExistAsync(loginModel.Egn))
            {
                ViewData["Title"] = "Вход";
                ModelState.AddModelError("", ModelErrorConstants.WrongLogin);
                return View(loginModel);
            }

            var result = await laboratoryPatientService.Login(loginModel);

            if (result.Succeeded)
            {
                return RedirectToAction("Index", "Home");
            }

            ViewData["Title"] = "Вход";
            ModelState.AddModelError("", ModelErrorConstants.ViewModelError);
            return View(loginModel);
        }

        [HttpGet]
        [Authorize(Roles = RoleConstants.LaboratoryUserRole)]
        public async Task<IActionResult> AllResult([FromQuery] ShowAllLaboratoryPatientResultViewModel query)
        {
            var userId = User.Id();

            var queryResult = await laboratoryPatientService.GetAllResult(
                userId,
                query.SearchTermDate,
                query.CurrentPage,
                ShowAllDoctorViewModel.DoctorsPerPage);

            ViewData["Title"] = "Всички резултати";

            query.TotalResultCount = queryResult.TotalResultCount;
            query.AllResults = queryResult.AllResults;

            return View(query);
        }

        [HttpGet]
        [Authorize(Roles = RoleConstants.LaboratoryUserRole)]
        public async Task<IActionResult> ViewResult(string id)
        {
            var modelResult = await laboratoryPatientService.GetResultByIdAsync(id);

            ViewData["Title"] = $"Резултат {id}";

            return View(modelResult);
        }

    }
}

MedicalCenter/Views/LaboratoryPatient/AllResult.cshtml
@model ShowAllLaboratoryPatientResultViewModel

@section Styles {
    <link href="~/css/date-picker.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/css/date-picker.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/font-awesome/css/all.min.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/css/adminlte.css" rel="stylesheet" asp-append-version="true" />
}

    <div class="offset-lg-4 offset-sm-4 col-lg-4 col-sm-4">
        <div class="small-box bg-gradient-secondary" style="height:120px;">
            <div class="row">
                <div class="col-8">
                    <div class="inner">
                        <h3 class="text-center" style="padding-top:10px;">@Model.TotalResultCount</h3>
                        <p class="text-center" style="font-size:14px;padding-left:5px;">@ViewData["Title"]</p>
                    </div>
                </div>
                <div class="col-4" style="position:center;padding-top:15px;">
                    <div class="icon">
                        <i class="fa fa-hourglass"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <table class="table">
            <thead style="background-color:#e6e6e6">
                <tr scope="col" colspan="12" class="text-center">
                    <th scope="col" colspan="12">Филтър по</th>
                </tr>
            </thead>
        </table>
        <form autocomplete="off" asp-controller="LaboratoryPatient" asp-action="AllResult" method="get">
            <div class="row">
                <div class="card-header col-sm-6 col-lg-6">
                    <div class="mx-0 mb-0 row justify-content-sm-center justify-content-start px-1">
                        <input asp-for="SearchTermDate" type="text" id="dp1" class="datepicker" placeholder="&#xf073; Избор на дата" style="font-family: Arial, FontAwesome, white;border: 1px solid #ced4da;" name="SearchTermDate" readonly />
                    </div>
                </div>

                <div class="card-header col-sm-2 col-lg-1">
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary">Търси</button>
                    </div>
                </div>

                <div class="card-header col-sm-4 col-lg-5">
                    <div class="form-group">

                        <a class="btn btn-warning" type="reset"
                       asp-controller="LaboratoryPatient"
                       asp-action="AllResult">Изчистване</a>
                    </div>
                </div>
            </div>
        </form>
    </div>
    @{
    var previousPage = Model.CurrentPage - 1;
    if (previousPage < 1)
    {
        previousPage = 1;
    }

    var maxPage = Math.Ceiling((double)Model.TotalResultCount /
        ShowAllLaboratoryPatientResultViewModel.ResultsPerPage);
}

@if (Model.TotalResultCount == 0)
{
    <h3 class="text-center" style="padding:50px;font-family:Monospace"><em>Няма записани часове за преглед!</em></h3>
}
else
{
    <table class="table table table-bordered">
        <thead style="background-color:#e6e6e6">
            <tr>
                <th scope="col" class="text-center">Дата</th>
                <th scope="col" class="text-center">Действие</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var result in Model.AllResults)
            {
                <partial name="_ResultPartial" model="@result" />
            }
        </tbody>
    </table>
}

<div class="row mt-2 col-12">
    <div class="col-lg-2 col-sm-2">
        <a class="btn btn-primary @(Model.CurrentPage == 1 ? "disabled" : string.Empty)"
           asp-controller="LaboratoryPatient"
           asp-action="AllResult"
           asp-route-searchTerm="@Model.SearchTermDate"
           asp-route-currentPage="@previousPage">Previous</a>
    </div>
    @{
        var shouldButtonBeDisabled = Model.CurrentPage == maxPage ||
        !Model.AllResults.Any();
    }
    <div class="offset-lg-9 offset-sm-9 col-lg-1 col-sm-1">
        <a class="btn btn-primary @(shouldButtonBeDisabled ? "disabled" : string.Empty)"
           asp-controller="LaboratoryPatient"
           asp-action="AllResult"
           asp-route-searchTerm="@Model.SearchTermDate"
           asp-route-currentPage="@(Model.CurrentPage+1)">Next</a>
    </div>
</div>

@section Scripts {
    <script src="~/js/bootstrap-datepicker.js" asp-append-version="true"></script>
    <script src="~/js/date-picker-pvevious.js" asp-append-version="true"></script>
    <partial name="_ValidationScriptsPartial" />
    <script>
        var date = new Date();
        $('#ClientTimeZoneOffset').val(date.getTimezoneOffset());
    </script>
}

MedicalCenter/Views/LaboratoryPatient/Login.cshtml
@model LoginPatientViewModel

@section Styles {
<link href="~/font-awesome/css/all.min.css" rel="stylesheet" asp-append-version="true" />
<link href="~/css/adminlte.css" rel="stylesheet" asp-append-version="true" />
}

<div class="container mt-5">
    <div class="row">
        <div class="login-box offset-lg-4 offset-sm-2 col-sm-8 col-lg-4">
            <div class="login-box">
                <div class="card card-outline card-primary">
                    <div class="card-header text-center">
                        <h1><b>@ViewData["Title"]</b></h1>
                    </div>
                    <div class="card-body">
                        <p class="login-box-msg">в Онлайн резултати</p>
                        <form method="post">
                            <div asp-validation-summary="ModelOnly" class="alert alert-danger alert-dismissible fade show"></div>
                            <div class="input-group mb-1">
                                <input asp-for="Egn" class="form-control" placeholder="ЕГН/Потребителско име" autocomplete="egn" />
                                <div class="input-group-append">
                                    <div class="input-group-text">
                                        <span class="fas fa-envelope"></span>
                                    </div>
                                </div>
                            </div>
                            <span asp-validation-for="Egn" class="text-danger"></span>
                            <div class="input-group mb-1 mt-3">
                                <input asp-for="Password" class="form-control" placeholder="Парола" autocomplete="password" />
                                <div class="input-group-append">
                                    <div class="input-group-text">
                                        <span class="fas fa-lock"></span>
                                    </div>
                                </div>
                            </div>
                            <span asp-validation-for="Password" class="text-danger mt-2"></span>
                            <div class="row">
                                <div class="col-4 offset-4 mt-3">
                                    <button type="submit" class="btn btn-primary btn-block">Вход</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

MedicalCenter/Views/LaboratoryPatient/ViewResult.cshtml
@model ResultViewModel

@section Styles {
    <link href="~/font-awesome/css/all.min.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/css/adminlte.css" rel="stylesheet" asp-append-version="true" />
}
    <div class="invoice p-3 mb-3">
        <!-- title row -->
        <div class="row">
            <div class="col-12">
                <h4>
                    <i class="fas fa-stethoscope"></i> Medical Center - Лаборатория
                    <small class="float-right">Дата: @Model.Date</small>
                </h4>
            </div>
            <!-- /.col -->
        </div>
        <!-- info row -->
        <div class="row invoice-info">
            <div class="col-sm-4 invoice-col">
                Пациент
                <address>
                    Име: <strong>@Model.PatientName</strong><br>
                </address>
            </div>
            <!-- /.col -->
            <div class="col-sm-4 invoice-col">
                <br />
                <address>
                    ЕГН: <strong>@Model.PatientEgn</strong><br>
                </address>
            </div>
        </div>
        <!-- /.row -->
        <!-- Table row -->
        <div class="row">
            <div class="col-12 table-responsive">
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>Име на изследване</th>
                            <th>Резултат</th>
                            <th>Единици</th>
                            <th>Референтни стойности</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>WBC (левкоцити)1</td>
                            <td>@Model.WBC</td>
                            <td>x10^9/L</td>
                            <td>3.50 - 10.50</td>
                        </tr>
                        <tr>
                            <td>RBC (еритроцити - бр.)</td>
                            <td>@Model.RBC</td>
                                <td>x10^12/L</td>
                            <td>3.70 - 5.30</td>
                        </tr>
                        <tr>
                            <td>Hgb (хемоглобин)</td>
                            <td>@Model.Hgb</td>
                            <td>g/L</td>
                            <td>120 - 160</td>
                        </tr>
                        <tr>
                            <td>Hct (хематокрит)</td>
                            <td>@Model.Hct</td>
                            <td>L/L</td>
                            <td>0.360 - 0.480</td>
                        </tr>
                        <tr>
                            <td>MCV (ср. обем на еритроцита)</td>
                            <td>@Model.MCV</td>
                            <td>fL</td>
                            <td>80.0 - 96.0</td>
                        </tr>
                        <tr>
                            <td>MCH (ср. Hbg съдърж. в еритр. )</td>
                            <td>@Model.MCH</td>
                            <td>pg</td>
                            <td>27.0 - 33.0</td>
                        </tr>
                        <tr>
                            <td>MCHC (ср. Hgb конц. в еритр.)</td>
                            <td>@Model.MCHC</td>
                            <td>g/L</td>
                            <td>300 - 600</td>
                        </tr>
                        <tr>
                            <td>Plt (трoмбоцити)</td>
                            <td>@Model.Plt</td>
                            <td>x10^9/L</td>
                            <td>130 - 140</td>
                        </tr>
                        <tr>
                            <td>Урина-pH(Urine-pH)</td>
                            <td>@Model.UrinepH</td>
                            <td>*</td>
                            <td>4.5 - 8.2</td>
                        </tr>
                        <tr>
                            <td>Урина - Относително тегло( Graviti)</td>
                            <td>@Model.UrineGravity</td>
                            <td>*</td>
                            <td>1.001 - 1.028</td>
                        </tr>
                    </tbody>
                </table>
                
            </div>
            <!-- /.col -->
        </div>
        <br/>
        <strong class="text-center">Край на справката.</strong>
        <br />
    </div>

MedicalCenter/Views/LaboratoryPatient/_ResultPartial.cshtml
@model DashboardLaboratoryPatientResultViewModel

<tr>
    <td scope="col">@Model.Date</td>
    <td scope="col" class="text-center">
        <form asp-controller="LaboratoryPatient" asp-action="ViewResult" method="get">
            <input name="id" type="hidden" value="@Model.TestId">
            <button type="submit" class="btn btn-warning">Виж</button>
        </form>
    </td>
</tr>