MedicalCenter/Controllers/LaborantController.cs
using MedicalCenter.Core.Contracts;
using MedicalCenter.Core.Models.Laborant;
using MedicalCenter.Infrastructure.Data.Common;
using MedicalCenter.Infrastructure.Data.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using static MedicalCenter.Infrastructure.Data.Global.DataConstants;

namespace MedicalCenter.Controllers
{

    [Authorize(Roles = RoleConstants.LaborantRole)]
    public class LaborantController : BaseController
    {
        private readonly ILaborantService laborantService;
        private readonly IGlobalService globalService;
        private readonly IRepository repository;

        public LaborantController(
            ILaborantService _laborantService,
            IGlobalService _globalService,
            IRepository _repository)
        {
            laborantService = _laborantService;
            globalService = _globalService;
            repository = _repository;
        }

        [HttpGet]
        public IActionResult SearchLaboratoryPatient()
        {
            var searchModel = new SearchLaboratoryPatientViewModel();

            ViewData["Title"] = "Проверка на съществуващ пациент по ЕГН";

            return View(searchModel);
        }

        [HttpPost]
        public async Task<IActionResult> SearchLaboratoryPatient(SearchLaboratoryPatientViewModel searchModel)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", ModelErrorConstants.ViewModelError);
                return View(searchModel);
            }

            var laboratoryPatient = await laborantService.SearchLaboratoryPatientByEgnAsync(searchModel.Egn);

            if (laboratoryPatient == null)
            {
                return RedirectToAction(nameof(CreateLaboratoryPatient));
            }

            ModelState.AddModelError("", ModelErrorConstants.LaboratoryPatientExistError);
            ViewData["Title"] = "Проверка на съществуващ пациент по ЕГН";
            return View(new SearchLaboratoryPatientViewModel());
        }

        [HttpGet]
        public async Task<IActionResult> CreateLaboratoryPatient()
        {
            var laboratoryPatientCreateModel = new CreateLaboratoryPatientViewModel();

            laboratoryPatientCreateModel.Genders = await globalService.GetGendersAsync();

            ViewData["Title"] = "Добавяне на потребител";

            return View(laboratoryPatientCreateModel);
        }

        [HttpPost]
        public async Task<IActionResult> CreateLaboratoryPatient(CreateLaboratoryPatientViewModel laboratoryPatientCreateModel)
        {
            laboratoryPatientCreateModel.Username = $"pat_{laboratoryPatientCreateModel.Egn}";

            if (!ModelState.IsValid)
            {
                laboratoryPatientCreateModel.Genders = await globalService.GetGendersAsync();
                ModelState.AddModelError("", ModelErrorConstants.ViewModelError);
                return View(laboratoryPatientCreateModel);
            }

            var result = await laborantService.CreateLaboratoryPatientAsync(laboratoryPatientCreateModel);

            var laboratoryPatient = await laborantService.GetLaboratoryPatientByEgnAsync(laboratoryPatientCreateModel.Egn);

            if (result.Succeeded)
            {
                await laborantService.AddLaboratoryPatientRoleAsync(laboratoryPatient.User, RoleConstants.LaboratoryUserRole);

                TempData[MessageConstant.SuccessMessage] = $"Успешно е добавен {laboratoryPatientCreateModel.FirstName} {laboratoryPatientCreateModel.LastName}!";

                return RedirectToAction(nameof(LaborantBoard));
            }

            foreach (var error in result.Errors)
            {
                ModelState.AddModelError("", error.Description);
            }

            laboratoryPatientCreateModel.Genders = await globalService.GetGendersAsync();

            return View(laboratoryPatientCreateModel);
        }

        [HttpGet]
        public IActionResult LaborantBoard()
        {
            ViewData["Title"] = "Laborant panel";

            return View();
        }

        [HttpGet]
        public async Task<IActionResult> AllLaboratoryPatient([FromQuery] ShowAllLaboratoryPatientViewModel query)
        {
            var queryResult = await laborantService.GetAllCurrentLaboratoryPatientAsync(
                query.SearchTermEgn,
                query.SearchTermName,
                query.CurrentPage,
                ShowAllLaboratoryPatientViewModel.LaboratoryPatientPerPage);

            ViewData["Title"] = "Всички пациенти";

            query.TotalLaboratoryPatientCount = queryResult.TotalLaboratoryPatientCount;
            query.LaboratoryPatients = queryResult.LaboratoryPatients;

            return View(query);
        }

        [HttpGet]
        public async Task<IActionResult> UploadResult(string patientId)
        {
            var laboratoryPatient = await repository.GetByIdAsync<LaboratoryPatient>(patientId);

            var model = new UploadTestResultViewModel
            {
                LaboratoryPatient = laboratoryPatient
            };

            ViewData["Title"] = $"Резултат на пациент с ЕГН: {laboratoryPatient.Egn}";

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> UploadResult(UploadTestResultViewModel model)
        {
            if (!ModelState.IsValid)
            {
                ViewData["Title"] = $"Резултат на пациент с ЕГН: {model.LaboratoryPatient.Egn}";
                ModelState.AddModelError("", ModelErrorConstants.ViewModelError);
                return View(model);
            }

            await laborantService.UploadResultAsync(model);
            return RedirectToAction(nameof(LaborantBoard));
        }
    }
}

MedicalCenter/Views/Laborant/AllLaboratoryPatient.cshtml
@model ShowAllLaboratoryPatientViewModel

@section Styles {
<link href="~/font-awesome/css/all.min.css" rel="stylesheet" asp-append-version="true" />
<link href="~/css/adminlte.css" rel="stylesheet" asp-append-version="true" />
<link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&amp;display=fallback">
}

<div class="offset-lg-4 offset-sm-4 col-lg-4 col-sm-4">
    <div class="small-box bg-success" style="height:100px;">
        <div class="row">
            <div class="col-8">
                <div class="inner">
                    <h3 class="text-center" style="padding-top:10px;">@Model.TotalLaboratoryPatientCount</h3>
                    <p class="text-center" style="font-size:14px;padding-left:5px;">@ViewData["Title"]</p>
                </div>
            </div>
            <div class="col-4" style="position:center;padding-top:15px;">
                <div class="icon">
                    <i class="fa fa-user-doctor"></i>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <table class="table">
        <thead style="background-color:#e6e6e6">
            <tr scope="col" colspan="12" class="text-center">
                <th scope="col" colspan="12">Филтър по</th>
            </tr>
        </thead>
    </table>
    <form autocomplete="off" method="get">
        <div class="row">
            
            <div class="card-header col-sm-3 col-lg-3">
                <div class="mx-0 mb-0 row justify-content-sm-center justify-content-start px-1">
                    <input asp-for="SearchTermEgn" class="form-control" placeholder="ЕГН">
                </div>
            </div>

            <div class="card-header col-sm-3 col-lg-3">
                <div class="mx-0 mb-0 row justify-content-sm-center justify-content-start px-1">
                    <input asp-for="SearchTermName" class="form-control" placeholder="Име пациент">
                </div>
            </div>

            <div class="card-header col-sm-2 col-lg-1">
                <div class="form-group">
                    <button type="submit" class="btn btn-primary">Търси</button>
                </div>
            </div>

            <div class="card-header col-sm-2 col-lg-2">
                <div class="form-group">
                    <a class="btn btn-warning" type="reset"
                       asp-controller="Laborant"
                       asp-action="AllLaboratoryPatient">Изчистване</a>
                </div>
            </div>
        </div>
    </form>
</div>

@{
    var previousPage = Model.CurrentPage - 1;
    if (previousPage < 1)
    {
        previousPage = 1;
    }

    var maxPage = Math.Ceiling((double)Model.TotalLaboratoryPatientCount /
        ShowAllLaboratoryPatientViewModel.LaboratoryPatientPerPage);
}

@if (Model.TotalLaboratoryPatientCount == 0)
{
    <h3 class="text-center" style="padding:50px;font-family:Monospace"><em>Няма намерени доктори по зададените критерии!</em></h3>
}
else
{
    <table class="table table table-bordered">
        <thead style="background-color:#e6e6e6">
            <tr>
                <th scope="row" class="text-center">Име на пациент</th>
                <th scope="row" class="text-center">ЕГН</th>
                <th scope="row" class="text-center">Телефон</th>
                <th scope="row" class="text-center">Регистриран на</th>
                <th scope="row" class="text-center">Действиe</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var patient in Model.LaboratoryPatients)
            {
                <partial name="_LaboratoryPatientPartial" model="@patient" />
            }
        </tbody>
    </table>
}
<div class="row mt-2 col-12">
    <div class="col-lg-2 col-sm-2">
        <a class="btn btn-primary @(Model.CurrentPage == 1 ? "disabled" : string.Empty)"
           asp-controller="Laborant"
           asp-action="AllLaboratoryPatient"
           asp-route-currentPage="@previousPage">Previous</a>
    </div>
    @{
        var shouldButtonBeDisabled = Model.CurrentPage == maxPage ||
        !Model.LaboratoryPatients.Any();
    }
    <div class="offset-lg-9 offset-sm-9 col-lg-1 col-sm-1">
        <a class="btn btn-primary @(shouldButtonBeDisabled ? "disabled" : string.Empty)"
           asp-controller="Laborant"
           asp-action="AllLaboratoryPatient"
           asp-route-currentPage="@(Model.CurrentPage+1)">Next</a>
    </div>
</div>

MedicalCenter/Views/Laborant/CreateLaboratoryPatient.cshtml
@model CreateLaboratoryPatientViewModel

@section Styles {
    <link href="~/font-awesome/css/all.min.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/css/adminlte.css" rel="stylesheet" asp-append-version="true" />
}
    <div class="container">
        <div class="row">
            <div class="register-box offset-lg-2 offset-sm-0 col-sm-12 col-lg-8">
                <div class="card card-outline card-primary">
                    <div class="card-header text-center">
                        <h1><b>Регистрация</b></h1>
                    </div>
                    <div class="card-body">
                        <p class="login-box-msg">@ViewData["Title"] в системата</p>
                        <form method="post">
                            <div asp-validation-summary="ModelOnly" class="alert alert-danger alert-dismissible fade show"></div>
                            
                            <div class="row">
                                <div class="col-sm-6 col-lg-6">
                                    <div class="input-group mb-1 mt-3">
                                        <input asp-for="Password" class="form-control" autocomplete="password" placeholder="Парола" />
                                        <div class="input-group-append">
                                            <div class="input-group-text">
                                                <span class="fas fa-lock"></span>
                                            </div>
                                        </div>
                                    </div>
                                    <span asp-validation-for="Password" class="text-danger"></span>
                                </div>
                                <div class="col-sm-6 col-lg-6">
                                    <div class="input-group mb-1 mt-3">
                                        <input asp-for="Egn" class="form-control" autocomplete="egn" placeholder="ЕГН" />
                                        <div class="input-group-append">
                                            <div class="input-group-text">
                                                <span class="fas fa-lock"></span>
                                            </div>
                                        </div>
                                    </div>
                                    <span asp-validation-for="Egn" class="text-danger"></span>
                                </div>
                                <input type="hidden" asp-for="Username" value="temporary" />
                            </div>
                            <div class="row">
                                <div class="col-sm-6 col-lg-6">
                                    <div class="input-group mb-1 mt-3">
                                        <input asp-for="FirstName" class="form-control" autocomplete="firstname" placeholder="Име" />
                                        <div class="input-group-append">
                                            <div class="input-group-text">
                                                <span class="fas fa-user"></span>
                                            </div>
                                        </div>
                                    </div>
                                    <span asp-validation-for="FirstName" class="text-danger"></span>
                                </div>
                                <div class="col-sm-6 col-lg-6">
                                    <div class="input-group mb-1 mt-3">
                                        <input asp-for="LastName" class="form-control" autocomplete="lastname" placeholder="Фамилия" />
                                        <div class="input-group-append">
                                            <div class="input-group-text">
                                                <span class="fas fa-user"></span>
                                            </div>
                                        </div>
                                    </div>
                                    <span asp-validation-for="LastName" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-6 col-lg-6">
                                    <div class="input-group mb-1 mt-3">
                                        <input asp-for="PhoneNumber" class="form-control" autocomplete="phonenumber" placeholder="+359888888888" />

                                        <div class="input-group-append">
                                            <div class="input-group-text">
                                                <span class="fas fa-mobile"></span>
                                            </div>
                                        </div>
                                    </div>
                                    <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                                </div>
                                <div class="col-sm-6 col-lg-6">
                                    <div class="input-group mb-1 mt-3">
                                        <select asp-for="Gender" class="form-control">
                                        @foreach (var gender in Model.Genders)
                                        {
                                            <option value="@gender.Id">@gender.Name</option>
                                        }
                                    </select>
                                    <div class="input-group-append">
                                        <div class="input-group-text">
                                            <span class="fas fa-venus"></span>
                                        </div>
                                    </div>
                                </div>
                                <span asp-validation-for="Gender" class="text-danger"></span>
                            </div>

                            <div class="offset-sm-2 offset-lg-3 col-sm-8 col-lg-5">
                                <div class="input-group mb-1 mt-5">
                                    <button type="submit" class="btn btn-primary btn-block">Регистрация</button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

MedicalCenter/Views/Laborant/LaborantBoard.cshtml
<h4 class="display-4 text-center">Панел:</h4>
<hr />
@section Styles {
<link href="~/font-awesome/css/all.min.css" rel="stylesheet" asp-append-version="true" />
<link href="~/css/adminlte.css" rel="stylesheet" asp-append-version="true" />
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&amp;display=fallback">
}

<div class="row">
    <div class="col-lg-6 col-6">
        <div class="small-box bg-gradient-info">
            <div class="row">
                <div class="col-8">
                    <div class="inner text-center">
                        <h3>Добави</h3>
                        <p>потребител</p>
                    </div>
                </div>
                <div class="col-4">
                    <div class="icon">
                        <i class="fa fa-user"></i>
                    </div>
                </div>
            </div>
            <a asp-controller="Laborant" asp-action="SearchLaboratoryPatient" class="small-box-footer">Добави <i class="fas fa-arrow-circle-right"></i></a>
        </div>
    </div>

    <div class="col-lg-6 col-6">
        <div class="small-box bg-gradient-success">
            <div class="row">
                <div class="col-8">
                    <div class="inner text-center">
                        <h3>Качи</h3>
                        <p>резултат</p>
                    </div>
                </div>
                <div class="col-4">
                    <div class="icon">
                        <i class="fa fa-vials" aria-hidden="true"></i>
                    </div>
                </div>
            </div>
            <a asp-controller="Laborant" asp-action="AllLaboratoryPatient" class="small-box-footer">Качи <i class="fas fa-arrow-circle-right"></i></a>
        </div>
    </div>
</div>

<div class="row mt-2" style="padding-top:20px;">
    <div class="offset-2 col-4">
        <article class="info">
            <figure class="icon text-center"><img src="~/images/register.jpg" alt=""></figure>
            <p class="text-center">
                <em>
                    <span>Регистрирани пациенти</span><br />
                </em>
            </p>
            <p class="text-center" id="total-patient"></p>
        </article>
    </div>
    <div class="col-4">
        <article class="info">
            <figure class="icon text-center"><img src="~/images/examination.jpg" alt=""></figure>
            <p class="text-center">
                <em>
                    <span>Направени теста</span><br />
                </em>
            </p>
            <p class="text-center" id="total-test"></p>
        </article>
    </div>
</div>


@section Scripts{
    <script>
        $.get('https://localhost:7183/api/statisticLaborant',(data)=>{
            $('#total-patient').text(data.allUserCount)
            $('#total-test').text(data.allTest)
        });
    </script>
}

MedicalCenter/Views/Laborant/SearchLaboratoryPatient.cshtml
@model SearchLaboratoryPatientViewModel


@section Styles {
    <link href="~/font-awesome/css/all.min.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/css/adminlte.css" rel="stylesheet" asp-append-version="true" />
}

    <div class="container mt-5">
        <div class="row">
            <div class="login-box offset-lg-4 offset-sm-2 col-sm-8 col-lg-4">
                <div class="login-box">
                    <div class="card card-outline card-primary">
                        <div class="card-header text-center">
                            <h1><b>@ViewData["Title"]</b></h1>
                        </div>
                        <div class="card-body">
                            <p class="login-box-msg">Търсене в системата</p>
                            <form asp-controller ="Laborant" asp-action="SearchLaboratoryPatient" method="post" >
                            <div asp-validation-summary="ModelOnly" class="alert alert-danger alert-dismissible fade show"></div>
                                <div class="input-group mb-1">
                                    <input asp-for="Egn" class="form-control" placeholder="ЕГН" autocomplete="egn" />
                                    <div class="input-group-append">
                                        <div class="input-group-text">
                                            <span class="fas fa-shield"></span>
                                        </div>
                                    </div>
                                </div>
                                <span asp-validation-for="Egn" class="text-danger"></span>
                                
                                <div class="row">
                                    <div class="col-4 offset-2 mt-3">
                                        <button type="submit" class="btn btn-primary btn-block">Търсене</button>
                                    </div>
                                    <div class="col-4 offset-0 mt-3">
                                        <a type="submit" class="btn btn-secondary" asp-controller="Laborant" asp-action="LaborantBoard">Назад</a>
                                    </div>
                                </div>
                            </form>
                            <p class="text-center text-muted mt-4 mb-0">
                                Преди да се регистрира нов пациент се проверява дали той вече не е бил регистриран в базата. Ако не е открит се регистрира.
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    @section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

MedicalCenter/Views/Laborant/UploadResult.cshtml
@model UploadTestResultViewModel

@section Styles {
    <link href="~/font-awesome/css/all.min.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/css/adminlte.css" rel="stylesheet" asp-append-version="true" />
}

<div class="container mt-5">
    <div class="row">
        <div class="login-box offset-lg-4 offset-sm-2 col-sm-8 col-lg-4">
            <div class="login-box">
                <div class="card card-outline card-primary">
                    <div class="card-header text-center">
                        <h1><b>@ViewData["Title"]</b></h1>
                    </div>
                    <div class="card-body">
                        <p class="login-box-msg">Качи</p>
                        <form method="post">
                            <div asp-validation-summary="ModelOnly" class="alert alert-danger alert-dismissible fade show"></div>
                            <input asp-for="LaboratoryPatient" type="hidden" value="@Model.LaboratoryPatient" />
                            <input asp-for="LaboratoryPatientId" type="hidden" value="@Model.LaboratoryPatient.Id" />
                            <div class="input-group mb-1">
                                <input asp-for="WBC" class="form-control" placeholder="WBC" autocomplete="WBC" />
                                <div class="input-group-append">
                                    <div class="input-group-text">
                                        <span class="fas fa-envelope"></span>
                                    </div>
                                </div>
                            </div>
                            <span asp-validation-for="WBC" class="text-danger"></span>
                            <div class="input-group mb-1">
                                <input asp-for="RBC" class="form-control" placeholder="RBC" autocomplete="RBC" />
                                <div class="input-group-append">
                                    <div class="input-group-text">
                                        <span class="fas fa-envelope"></span>
                                    </div>
                                </div>
                            </div>
                            <span asp-validation-for="RBC" class="text-danger mt-2"></span>

                            <div class="input-group mb-1">
                                <input asp-for="Hgb" class="form-control" placeholder="Hgb" autocomplete="Hgb" />
                                <div class="input-group-append">
                                    <div class="input-group-text">
                                        <span class="fas fa-envelope"></span>
                                    </div>
                                </div>
                            </div>
                            <span asp-validation-for="Hgb" class="text-danger mt-2"></span>
                            <div class="input-group mb-1">
                                <input asp-for="Hct" class="form-control" placeholder="Hct" autocomplete="Hct" />
                                <div class="input-group-append">
                                    <div class="input-group-text">
                                        <span class="fas fa-envelope"></span>
                                    </div>
                                </div>
                            </div>
                            <span asp-validation-for="Hct" class="text-danger mt-2"></span>
                            <div class="input-group mb-1">
                                <input asp-for="MCV" class="form-control" placeholder="MCV" autocomplete="MCV" />
                                <div class="input-group-append">
                                    <div class="input-group-text">
                                        <span class="fas fa-envelope"></span>
                                    </div>
                                </div>
                            </div>
                            <span asp-validation-for="MCV" class="text-danger mt-2"></span>
                            <div class="input-group mb-1">
                                <input asp-for="MCH" class="form-control" placeholder="MCH" autocomplete="MCH" />
                                <div class="input-group-append">
                                    <div class="input-group-text">
                                        <span class="fas fa-envelope"></span>
                                    </div>
                                </div>
                            </div>
                            <span asp-validation-for="MCH" class="text-danger mt-2"></span>
                            <div class="input-group mb-1">
                                <input asp-for="MCHC" class="form-control" placeholder="MCHC" autocomplete="MCHC" />
                                <div class="input-group-append">
                                    <div class="input-group-text">
                                        <span class="fas fa-envelope"></span>
                                    </div>
                                </div>
                            </div>
                            <span asp-validation-for="MCHC" class="text-danger mt-2"></span>
                            <div class="input-group mb-1">
                                <input asp-for="Plt" class="form-control" placeholder="Plt" autocomplete="Plt" />
                                <div class="input-group-append">
                                    <div class="input-group-text">
                                        <span class="fas fa-envelope"></span>
                                    </div>
                                </div>
                            </div>
                            <span asp-validation-for="Plt" class="text-danger mt-2"></span>

                            <div class="input-group mb-1">
                                <input asp-for="UrinepH" class="form-control" placeholder="UrinepH" autocomplete="UrinepH" />
                                <div class="input-group-append">
                                    <div class="input-group-text">
                                        <span class="fas fa-envelope"></span>
                                    </div>
                                </div>
                            </div>
                            <span asp-validation-for="UrinepH" class="text-danger mt-2"></span>
                            <div class="input-group mb-1">
                                <input asp-for="UrineGravity" class="form-control" placeholder="UrineGravity" autocomplete="UrineGravity" />
                                <div class="input-group-append">
                                    <div class="input-group-text">
                                        <span class="fas fa-envelope"></span>
                                    </div>
                                </div>
                            </div>
                            <span asp-validation-for="UrineGravity" class="text-danger mt-2"></span>
                            <div class="row">
                                <div class="col-4 offset-4 mt-3">
                                    <button type="submit" class="btn btn-primary btn-block">Качи</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

MedicalCenter/Views/Laborant/_LaboratoryPatientPartial.cshtml
@model DashboardLaboratoryPatientViewModel

<tr>
    <td scope="col">@Model.FirstName @Model.LastName</td>
    <td scope="col">@Model.Egn</td>
    <td scope="col" class="text-center">@Model.PhoneNumber</td>
    <td scope="col" class="text-center">@Model.JoinOnDate</td>
    <td scope="col" class="text-center">
        <form asp-controller="Laborant" asp-action="UploadResult" method="get">
            <input name="patientId" type="hidden" value="@Model.Id">
            <button type="submit" class="btn btn-warning">Качи</button>
        </form>
    </td>
</tr>