MedicalCenter/Controllers/DoctorController.cs
using MedicalCenter.Core.Contracts;
using MedicalCenter.Core.Models.Dotor;
using MedicalCenter.Extensions;
using MedicalCenter.Infrastructure.Data.Common;
using MedicalCenter.Infrastructure.Data.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using static MedicalCenter.Infrastructure.Data.Global.DataConstants;

namespace MedicalCenter.Controllers
{
    [Authorize(Roles = RoleConstants.DoctorRole)]
    public class DoctorController : BaseController
    {
        private readonly IDoctorService doctorService;
        private readonly IRepository repository;

        public DoctorController(
            IDoctorService _doctorService,
            IRepository _repository)
        {
            doctorService = _doctorService;
            repository = _repository;
        }

        [HttpGet]
        public async Task<IActionResult> DoctorBoard()
        {
            ViewData["Title"] = "Табло на ";

            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", ModelErrorConstants.ViewModelError);
                ViewData["Title"] = "Табло на ";
                return View();
            }

            var doctorId = User.Id();

            if (doctorId == null)
            {
                ModelState.AddModelError("", ModelErrorConstants.ViewModelError);
                ViewData["Title"] = "Табло на ";
                return View();
            }

            var doctor = await doctorService.GetDoctorByIdAsync(doctorId);

            if (doctor == null)
            {
                ModelState.AddModelError("", ModelErrorConstants.ViewModelError);
                ViewData["Title"] = "Табло на ";
                return View();
            }

            ViewData["DoctorName"] = $"д-р {doctor.User.FirstName} {doctor.User.LastName}";

            return View();
        }

        [HttpGet]
        public async Task<IActionResult> DoctorStatistic()
        {
            ViewData["Title"] = "Табло на ";

            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", ModelErrorConstants.ViewModelError);
                ViewData["Title"] = "Табло на ";
                return View();
            }

            var doctorId = User.Id();

            if (doctorId == null)
            {
                ModelState.AddModelError("", ModelErrorConstants.ViewModelError);
                ViewData["Title"] = "Табло на ";
                return View();
            }

            var doctor = await doctorService.GetDoctorByIdAsync(doctorId);

            if (doctor == null)
            {
                ModelState.AddModelError("", ModelErrorConstants.ViewModelError);
                ViewData["Title"] = "Табло на ";
                return View();
            }

            var allExaminationModel = new DoctorExaminationInfo
            {
                DoctorExaminations = await doctorService.GetAllExaminationAsync(doctor),
                DoctorStatistics = await doctorService.GetDoctorStatisticsAsync(doctor),
            };

            return View(allExaminationModel);
        }

        [HttpGet]
        public async Task<IActionResult> AllDoctorExamination([FromQuery]ShowAllExaminationDoctorViewModel query)
        {
            var doctor = await doctorService.GetDoctorByIdAsync(User.Id());

            var queryResult = await doctorService.GetAllDoctorExaminationAsync(
                doctor.Id, 
                query.SearchTerm, 
                query.CurrentPage, 
                ShowAllExaminationDoctorViewModel.ExaminationPerPage);

            if (string.IsNullOrEmpty(query.SearchTerm) == false)
            {
                ViewData["Title"] = $"Записани прегледи на {query.SearchTerm}";
            }
            else
            {
                ViewData["Title"] = $"Записани прегледи";
            }

            query.TotalExaminationCount = queryResult.TotalExaminationCount;
            query.AllExamination = queryResult.AllExamination;

            return View(query);
        }
    }
}

MedicalCenter/Controllers/ReviewController.cs
using MedicalCenter.Core.Contracts;
using MedicalCenter.Core.Models.Review;
using MedicalCenter.Extensions;
using MedicalCenter.Infrastructure.Data.Common;
using MedicalCenter.Infrastructure.Data.Models;
using Microsoft.AspNetCore.Mvc;

namespace MedicalCenter.Controllers
{
    public class ReviewController : BaseController
    {
        private readonly IReviewService reviewService;
        private readonly IGlobalService globalService;
        private readonly IRepository repository;
        private readonly IDoctorService doctorService;

        public ReviewController(
            IReviewService _reviewService, 
            IGlobalService _globalService,
            IRepository _repository,
            IDoctorService _doctorService)
        {
            reviewService = _reviewService;
            globalService = _globalService;
            repository = _repository;
            doctorService = _doctorService;
        }

        [HttpGet]
        public async Task<IActionResult> CreateReview(string examinationId)
        {
            var examination = await repository.GetByIdAsync<Examination>(examinationId);
            var reviewModel = new ReviewViewModel();
            reviewModel.ExaminationId=examinationId;
            reviewModel.UserId = examination.UserId;
            reviewModel.DoctorId = examination.DoctorId;
            ViewData["Title"] = $"Оценка за прегледа при {examination.DoctorFullName} проведен на {examination.Date.ToString("dd.MM.yyyy")} {examination.Hour}";
            return View(reviewModel);
        }

        [HttpPost]
        public async Task<IActionResult> CreateReview(ReviewViewModel reviewModel)
        {
            if (!ModelState.IsValid)
            {
                var examination = await repository.GetByIdAsync<Examination>(reviewModel.ExaminationId);
                ViewData["Title"] = $"Оценка за прегледа при {examination.DoctorFullName} проведен на {examination.Date.ToString("dd.MM.yyyy")} {examination.Hour}";
                return View(reviewModel);
            }

            await reviewService.CreateReviewAsync(reviewModel);

            return RedirectToAction("ExaminationForFeedback", "User");
        }

        [HttpGet]
        public async Task<IActionResult> AllGiveReview(ShowAllGiveReviewViewModel query)
        {
            var userId = User.Id();

            ViewData["Title"] = $"Всички оценки";

            var queryResult = await reviewService.GetAllGiveReviewsByUserAsync(
                userId, 
                query.Specialty,
                query.SearchTermDate,
                query. SearchTermName,
                query.CurrentPage,
                ShowAllGiveReviewViewModel.ReviewPerPage);

            query.TotalReviewsCount = queryResult.TotalReviewsCount;
            query.Reviews = queryResult.Reviews;
            query.Specialties = await globalService.GetSpecialtiesAsync();

            return View(query);
        }

        [HttpGet]
        public async Task<IActionResult> AllReceiveReview([FromQuery]ShowAllReceiveReviewViewModel query)
        {
            var doctor = await doctorService.GetDoctorByIdAsync(User.Id());
            
            var queryResult = await reviewService.GetReceiveReviewsByDoctorIdAsync(
                doctor.Id,
                query.SearchTerm,
                query.CurrentPage,
                ShowAllReceiveReviewViewModel.ReviewPerPage);

            ViewData["Title"] = $"Получени оценки";

            query.TotalReviewsCount = queryResult.TotalReviewsCount;
            query.Reviews = queryResult.Reviews;

            return View(query);
        }

        [HttpGet]
        public async Task<IActionResult> AllReview([FromQuery]ShowAllReviewViewModel query)
        {
            var queryResult = await reviewService.GetAllReviewsAsync(
                query.Speciality,
                query.SearchTermName,
                query.SearchTermRating,
                query.CurrentPage,
                ShowAllReviewViewModel.ReviewPerPage);

            ViewData["Title"] = "Всички оценки";

            query.TotalReviewsCount = queryResult.TotalReviewsCount;
            query.Reviews = queryResult.Reviews;
            query.Specialties = await globalService.GetSpecialtiesAsync();
            return View(query);

        }
    }
}

MedicalCenter/Views/Doctor/AllDoctorExamination.cshtml
@model ShowAllExaminationDoctorViewModel

@section Styles {
    <link href="~/css/date-picker.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/css/date-picker.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/font-awesome/css/all.min.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/css/adminlte.css" rel="stylesheet" asp-append-version="true" />
}

    <div class="offset-lg-4 offset-sm-4 col-lg-4 col-sm-4">
        <div class="small-box bg-gradient-secondary" style="height:120px;">
            <div class="row">
                <div class="col-8">
                    <div class="inner">
                        <h3 class="text-center" style="padding-top:10px;">@Model.TotalExaminationCount</h3>
                        <p class="text-center" style="font-size:14px;padding-left:5px;">@ViewData["Title"]</p>
                    </div>
                </div>
                <div class="col-4" style="position:center;padding-top:15px;">
                    <div class="icon">
                        <i class="fa fa-hourglass"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <table class="table">
            <thead style="background-color:#e6e6e6">
                <tr scope="col" colspan="12" class="text-center">
                    <th scope="col" colspan="12">Филтър по</th>
                </tr>
            </thead>
        </table>
        <form autocomplete="off" asp-controller="Doctor" asp-action="AllDoctorExamination" method="get">
            <div class="row">
                <div class="card-header col-sm-6 col-lg-6">
                    <div class="mx-0 mb-0 row justify-content-sm-center justify-content-start px-1">
                        <input asp-for="SearchTerm" type="text" id="dp1" class="datepicker" placeholder="&#xf073; Избор на дата" style="font-family: Arial, FontAwesome, white;border: 1px solid #ced4da;" name="SearchTerm" readonly />
                    </div>
                </div>

                <div class="card-header col-sm-2 col-lg-1">
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary">Търси</button>
                    </div>
                </div>

                <div class="card-header col-sm-4 col-lg-5">
                    <div class="form-group">

                        <a class="btn btn-warning" type="reset"
                       asp-controller="Doctor"
                       asp-action="AllDoctorExamination">Изчистване</a>
                    </div>
                </div>
            </div>
        </form>
    </div>
    @{
    var previousPage = Model.CurrentPage - 1;
    if (previousPage < 1)
    {
        previousPage = 1;
    }

    var maxPage = Math.Ceiling((double)Model.TotalExaminationCount /
        ShowAllExaminationDoctorViewModel.ExaminationPerPage);
}

@if (Model.TotalExaminationCount == 0)
{
    <h3 class="text-center" style="padding:50px;font-family:Monospace"><em>Няма записани часове за преглед!</em></h3>
}
else
{
    <table class="table table table-bordered">
        <thead style="background-color:#e6e6e6">
            <tr>
                <th scope="col" class="text-center">Дата</th>
                <th scope="col" class="text-center">Час</th>
                <th scope="col" class="text-center">Име на пациент</th>
                <th scope="col" class="text-center">Телефон</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var examination in Model.AllExamination)
            {
                <partial name="_DoctorExaminationPartial" model="@examination" />
            }
        </tbody>
    </table>
}

<div class="row mt-2 col-12">
    <div class="col-lg-2 col-sm-2">
        <a class="btn btn-primary @(Model.CurrentPage == 1 ? "disabled" : string.Empty)"
           asp-controller="Doctor"
           asp-action="AllDoctorExamination"
           asp-route-searchTerm="@Model.SearchTerm"
           asp-route-currentPage="@previousPage">Previous</a>
    </div>
    @{
        var shouldButtonBeDisabled = Model.CurrentPage == maxPage ||
        !Model.AllExamination.Any();
    }
    <div class="offset-lg-9 offset-sm-9 col-lg-1 col-sm-1">
        <a class="btn btn-primary @(shouldButtonBeDisabled ? "disabled" : string.Empty)"
           asp-controller="Doctor"
           asp-action="AllDoctorExamination"
           asp-route-searchTerm="@Model.SearchTerm"
           asp-route-currentPage="@(Model.CurrentPage+1)">Next</a>
    </div>
</div>

@section Scripts {
    <script src="~/js/bootstrap-datepicker.js" asp-append-version="true"></script>
    <script src="~/js/date-picker-pvevious.js" asp-append-version="true"></script>
    <partial name="_ValidationScriptsPartial" />
    <script>
        var date = new Date();
        $('#ClientTimeZoneOffset').val(date.getTimezoneOffset());
    </script>
}

MedicalCenter/Views/Doctor/DoctorBoard.cshtml
<h3 class="display-4 text-center">@ViewData["Title"] @ViewData["DoctorName"]</h3>
<hr />
@section Styles {
<link href="~/font-awesome/css/all.min.css" rel="stylesheet" asp-append-version="true" />
<link href="~/css/adminlte.css" rel="stylesheet" asp-append-version="true" />
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&amp;display=fallback">
}

<div class="row">
    <div class="col-lg-8 col-8">
        <div class="small-box bg-gradient-info">
            <div class="row">
                <div class="col-8">
                    <div class="inner text-center">
                        <h3>@ViewData["DoctorName"]</h3>
                        <p>статистика</p>
                    </div>
                </div>
                <div class="col-4">
                    <div class="icon">
                        <i class="fa fa-user-md"></i>
                    </div>
                </div>
            </div>
            <a asp-controller="Doctor" asp-action="DoctorStatistic" class="small-box-footer">Виж <i class="fas fa-arrow-circle-right"></i></a>
        </div>
    </div>

    <div class="col-lg-4 col-4">
        <div class="small-box bg-gradient-success">
            <div class="row">
                <div class="col-8">
                    <div class="inner text-center">
                        <h3>Записани</h3>
                        <p>прегледи</p>
                    </div>
                </div>
                <div class="col-4">
                    <div class="icon">
                        <i class="fa fa-database" aria-hidden="true"></i>
                    </div>
                </div>
            </div>
            <a asp-controller="Doctor" asp-action="AllDoctorExamination" class="small-box-footer">Покажи <i class="fas fa-arrow-circle-right"></i></a>
        </div>
    </div>
</div>

MedicalCenter/Views/Doctor/DoctorStatistic.cshtml
@model DoctorExaminationInfo

<h3 class="display-4 text-center">@ViewData["Title"] @Model.DoctorStatistics.DoctorFullName</h3>
<hr />

<div class="row mt-5">

    <div class=col-4>
        <article class="info">
            <figure class="icon"><img src="~/images/examination.jpg" alt=""></figure>

            <p class="text-center">
                <em>
                    @Model.DoctorStatistics.Examinations<br />
                    <span>Извършени прегледа</span>
                </em>
            </p>
        </article>
    </div>
    <div class=col-4>
        <article class="info">
            <figure class="icon"><img src="~/images/allexamination.jpg" alt=""></figure>
            <p class="text-center">
                <em>@Model.DoctorStatistics.AllExaminations</em> <br />
                <em><span>Записани за преглед</span></em>
            </p>
        </article>
    </div>
    <div class=col-4>
        <article class="info">
            <figure class="icon"><a asp-controller="Review" asp-action="AllReceiveReview"><img src="~/images/starrating.png" alt="Всички оценки" style="padding-left:15px;width:92px;"></a></figure>
            <p class="text-center">
                <em>@Model.DoctorStatistics.Rating/5 - @Model.DoctorStatistics.RatingUser оценки</em> <br />

                <em><span>Рейтинг</span></em>
            </p>
        </article>
    </div>
</div>

MedicalCenter/Views/Doctor/_DoctorExaminationPartial.cshtml
@model DashboardDoctorExaminationViewModel

<tr>
    <td scope="col">@Model.Date</td>
    <td scope="col">@Model.Hour</td>
    <td scope="col">@Model.UserFullName</td>
    <td scope="col" class="text-center">@Model.UserPhoneNumber</td>
</tr>